---
- hosts: all
  become: true
  tasks:
    - name: Update Cache
      apt: update_cache=true
    - name: Install Dependicies
      apt: name={{ item }} state=present
      with_items:
        - git
        - default-jdk
        - python3
        - python3-pip
    - name: Install Python Packages
      pip: name={{ item }} state=present executable=pip3
      with_items:
        - django