Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/trusty64"

    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "192.168.56.101"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "puppet_master"
    end

    config.vm.provision "shell", inline: <<-SHELL

    cd ~; wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
    sudo dpkg -i puppetlabs-release-trusty.deb
    sudo apt update

    sudo apt install -y puppetmaster-passenger

    sudo service apache2 stop

    SHELL

  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "bento/fedora-27"

    agent1.vm.hostname = "agent1"
    agent1.vm.network :private_network, ip: "192.168.56.102"

    agent1.vm.provider "virtualbox" do |vb|
      vb.name = "puppet_agent_1"
    end
  end
end
