Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-27"
  config.vm.network "forwarded_port", guest: 30080, host: 30080

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.name = "pachyderm_test"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

  end
