---
- hosts: all
  become: true
  gather_facts: no

  pre_tasks:
    - name: 'Install Python'
      raw: sudo dnf -y install python

  tasks:
    - name: Install Dependicies
      dnf: name={{ item }} state=present
      with_items:
        - java-1.8.0-openjdk

    - name: Download Kafka
      # https://kafka.apache.org/quickstart
      unarchive:
        src: http://apache.mirror.anlx.net/kafka/1.1.0/kafka_2.11-1.1.0.tgz
        dest: /home/vagrant/
        remote_src: yes

    - name: Start Zookeeper
      shell: bin/zookeeper-server-start.sh config/zookeeper.properties
      # https://ansibledaily.com/execute-detached-process-with-ansible/
      async: 2592000
      poll: 0
      args:
        chdir: /home/vagrant/kafka_2.11-1.1.0/
        
    - name: Start Kafka
      shell: bin/kafka-server-start.sh config/server.properties
      # https://ansibledaily.com/execute-detached-process-with-ansible/
      async: 2592000
      poll: 0
      args:
        chdir: /home/vagrant/kafka_2.11-1.1.0/

